# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Agencias Busplus
    url: https://agencias.busplus.com.ar
  - name: Webservices Busplus
    url: https://ws.busplus.com.ar
  - name: Viabariloche.com.ar
    url: https://viabariloche.com.ar
  - name: Web Catedral
    url: https://catedralaltapatagonia.com
  - name: TCP ping 249
    url: 181.47.187.249

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: viabgit.github.io/apptime
  # Uncomment the following line if you don't havehttps://viabgit.github.io/apptime/ a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://f000.backblazeb2.com/file/Publicos/Busplus_logo_sl.png
  name: Upptime
  introTitle: "**Viaupptime** Estado de servicios de Busplus"
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
